package <%= package %>

import org.json4s.{DefaultFormats, Formats}
import org.scalatra.json._
import org.scalatra._

class <%= servletName %> extends ScalatraServlet with ScalatraBase with JacksonJsonSupport {

  protected implicit val jsonFormats: Formats = DefaultFormats

  case class Message(body: String)

  before() {
    contentType = formats("json")
  }

  get("/messages") {
    List(Message("Great job!"), Message("Scalatra project generated by Yeoman!"))
  }

}